import type { Metadata } from "next";
import "../globals.css";
import Header from "../(components)/Header";
import Footer from "../(components)/Footer";

export const metadata: Metadata = {
  title: "Transpot marketplace",
  description: "Generated by create next app",
};

export default function WebsiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Header/>
      
        {children}
      <Footer/>
      </body>
    </html>
  );
}
